export enum BillSubTypes {
  MAINTENACE = 'MAINTENACE',
  PURCHASES = 'PURCHASES',
  THIRD_PARTY_SERVICES = 'THIRD_PARTY_SERVICES',
  TOOLS = 'TOOLS',
  ESSENTIAL_SERVICES = 'ESSENTIAL_SERVICES',
  TAXES = 'TAXES',
  FEES = 'FEES',
  OTHERS = 'OTHERS',
}
